# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b225b90011f0ce17dae9a381b3383fc123328f8d561382719bf6ca4447e38fff4f6b83972e2283b7a8c92bed28e4b77665a0f64c49aa21e4e0713fcbad7c06c

test:
  secret_key_base: a99b60314f0ff053ab4599a3c0bf3e3f52dbdb9c2de8d6cdd8098c7682c12ecc9f77ef51b15f52fabd3e7aa1a8ef377146638b509ec0cdf16d5425b3cd2b6da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
